# Generated by Django 3.2.6 on 2021-08-30 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.departmentmodel'),
        ),
    ]
